--
--
-- Table: users
create table
    public.users (
        id uuid references auth.users on delete cascade not null primary key,
        profile jsonb,
        metadata jsonb,
        created_at timestamp with time zone default timezone ('utc'::text, now()) not null,
        updated_at timestamp with time zone default timezone ('utc'::text, now()) not null
    );
comment on table public.users is 'User info and profile';
comment on column public.users.id is 'References the internal Supabase Auth user';
--
--
-- Table: user_sources
create table
    public.reports (
        id uuid primary key,
        -- user_id uuid references public.users on delete cascade not null,        
        created_at timestamp with time zone default timezone ('utc'::text, now()) not null,
        updated_at timestamp with time zone default timezone ('utc'::text, now()) not null,
    );
comment on table public.reports is 'Stores reports generated by users for tracking and analysis';
comment on column public.reports.id is 'Unique identifier for each report';
comment on column public.reports.created_at is 'Timestamp when the report was created';
comment on column public.reports.updated_at is 'Timestamp when the report was last updated';
