-- Table: users
create table
    public.users (
        id uuid references auth.users on delete cascade not null primary key,
        profile jsonb,
        metadata jsonb,
        created_at timestamp with time zone default timezone ('utc'::text, now()) not null,
        updated_at timestamp with time zone default timezone ('utc'::text, now()) not null
    );
comment on table public.users is 'User info and profile';
comment on column public.users.id is 'References the internal Supabase Auth user';

--
--
-- Table: 
create table
    public.reports (
        id uuid primary key,
        job_title text,
        job_description text,
        job_requirements text[],
        job_skills text[],
        job_responsibilities text[],
        job_tasks uuid[],
        report_status text,
        created_at timestamp with time zone default timezone ('utc'::text, now()) not null,
        updated_at timestamp with time zone default timezone ('utc'::text, now()) not null
    );
comment on table public.reports is 'Stores reports generated by users for tracking and analysis';
comment on column public.reports.id is 'Unique identifier for each report';
comment on column public.reports.job_title is 'The title of the job';
comment on column public.reports.job_description is 'The description of the job';
comment on column public.reports.job_requirements is 'The requirements of the job';
comment on column public.reports.job_skills is 'The skills required for the job';
comment on column public.reports.job_responsibilities is 'The responsibilities of the job';
comment on column public.reports.job_tasks is 'The tasks required for the job';
comment on column public.reports.created_at is 'Timestamp when the report was created';
comment on column public.reports.updated_at is 'Timestamp when the report was last updated';
--
--
-- Table: user_requests
create table
    public.user_requests (
        report_id uuid references public.reports not null,
        user_id uuid references public.users not null,
        created_at timestamp with time zone default timezone ('utc'::text, now()) not null      
    );
comment on column public.user_requests.report_id is 'Unique identifier for each report request';
comment on column public.user_requests.user_id is 'References the internal Supabase Auth user';
comment on column public.user_requests.created_at is 'Timestamp when the request was created';
-- 
-- 
-- Table: job_tasks
create table
    public.job_tasks (
        id uuid primary key,
        report_id uuid references public.reports not null,
        task text,
        description text,
        sub_tasks uuid[],
        time_percentage float,
        created_at timestamp with time zone default timezone ('utc'::text, now()) not null      
    );
comment on table public.job_tasks is 'Stores job tasks for tracking and analysis';
comment on column public.job_tasks.id is 'Unique identifier for each job task';
comment on column public.job_tasks.report_id is 'References the report';
comment on column public.job_tasks.task is 'The title name of the task';
comment on column public.job_tasks.description is 'The description of the task';
comment on column public.job_tasks.sub_tasks is 'The sub tasks of the task';
comment on column public.job_tasks.time_percentage is 'The percentage of time the task takes';
comment on column public.job_tasks.created_at is 'Timestamp when the task was created';
--
--
-- Table: job_sub_tasks
create table
    public.job_sub_tasks (
        id uuid primary key,
        task_id uuid references public.job_tasks not null,
        sub_task text,
        description text,
        llm_prompt text,
        created_at timestamp with time zone default timezone ('utc'::text, now()) not null
    );
comment on table public.job_sub_tasks is 'Stores job sub tasks for tracking and analysis';
comment on column public.job_sub_tasks.id is 'Unique identifier for each job sub task';
comment on column public.job_sub_tasks.task_id is 'References the job task';
comment on column public.job_sub_tasks.sub_task is 'The title name of the sub task';
comment on column public.job_sub_tasks.description is 'The description of the sub task';
comment on column public.job_sub_tasks.llm_prompt is 'The system prompt used to create the agent for the sub task';
comment on column public.job_sub_tasks.created_at is 'Timestamp when the sub task was created';
